spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/derliderli?serverTimezone=GMT%2B8&allowMultiQueries=true&autoRec&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
rocketmq:
    name:
      server:
        address: 127.0.0.1:9876